# Generated by Django 5.2.3 on 2025-06-29 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('weekly_fee', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Monto semanal')),
                ('total_weeks', models.PositiveIntegerField(verbose_name='Cantidad de semanas')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='cars.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.client')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('client',), name='unique_active_contract_per_client'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('car',), name='unique_active_contract_per_car')],
            },
        ),
    ]
