# Generated by Django 5.2.3 on 2025-06-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='weekly_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monto semanal'),
        ),
    ]
