# Generated by Django 5.2.3 on 2025-07-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carbrand_alter_car_brand_carmodel_alter_car_model'),
        ('clients', '0002_rename_name_client_first_name'),
        ('contracts', '0003_invoice'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='unique_active_contract_per_client',
        ),
        migrations.RemoveConstraint(
            model_name='contract',
            name='unique_active_contract_per_car',
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('client',), name='unique_active_contract_per_client'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('car',), name='unique_active_contract_per_car'),
        ),
    ]
