# Generated by Django 5.2.3 on 2025-07-03 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_options_alter_carbrand_options_and_more'),
        ('clients', '0002_rename_name_client_first_name'),
        ('contracts', '0005_remove_contract_unique_active_contract_per_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='cars.car', verbose_name='Auto'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.client', verbose_name='Cliente'),
        ),
    ]
