# Generated by Django 5.2.3 on 2025-07-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_brand_alter_car_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Auto', 'verbose_name_plural': 'Autos'},
        ),
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Modelo', 'verbose_name_plural': 'Modelos'},
        ),
    ]
